use std::{ffi::OsString, fs};

use vibe_cs_hlae::{
    HLAE_MANAGED_SESSION_CONFIG_RELATIVE_PATH, HlaeDiscoverySource, HlaeInstallation,
    LaunchResolution, build_hlae_launch_profile, build_hlae_managed_session_invocation,
    compile_hlae_managed_session_bootstrap,
};

#[test]
fn compiles_one_fixed_offline_startup_config_that_loads_evidence_before_the_demo() {
    let root = tempfile::tempdir().unwrap();
    let job = root.path().join("job");
    let artifacts = job.join("artifacts");
    fs::create_dir_all(&artifacts).unwrap();
    let demo = root.path().join("major.dem");
    let commands = artifacts.join("vibe_cs_commands.xml");
    let bridge = artifacts.join("vibe_cs_bridge.js");
    fs::write(&demo, b"demo").unwrap();
    fs::write(&commands, b"commands").unwrap();
    fs::write(&bridge, b"bridge").unwrap();

    let bootstrap =
        compile_hlae_managed_session_bootstrap(&job, &demo, &commands, &bridge).unwrap();

    assert_eq!(
        bootstrap.path(),
        job.join(HLAE_MANAGED_SESSION_CONFIG_RELATIVE_PATH)
    );
    let contents = bootstrap.contents();
    let command_path = commands.display().to_string();
    let bridge_path = bridge.display().to_string();
    let demo_path = demo.display().to_string();
    assert_eq!(
        contents,
        format!(
            "// Generated by Vibe CS for one managed, offline HLAE session.\n\
             mirv_cmd clear\n\
             mirv_cmd load \"{command_path}\"\n\
             mirv_cmd enabled 1\n\
             mirv_script_load \"{bridge_path}\"\n\
             playdemo \"{demo_path}\"\n"
        )
    );
    assert!(!contents.contains("demo_gototick"));
    assert!(!contents.contains("connect "));
}

#[test]
fn managed_invocation_passes_only_the_fixed_validated_startup_commands() {
    let root = tempfile::tempdir().unwrap();
    let job = root.path().join("job");
    let cfg = job.join("cfg");
    let artifacts = job.join("artifacts");
    let installation_root = root.path().join("hlae");
    let hlae = installation_root.join("HLAE.exe");
    let hook = installation_root.join("x64/AfxHookSource2.dll");
    let game = root.path().join("game/bin/win64/cs2.exe");
    let steam = root.path().join("Steam/steam.exe");
    for directory in [
        &cfg,
        &artifacts,
        hook.parent().unwrap(),
        game.parent().unwrap(),
        steam.parent().unwrap(),
    ] {
        fs::create_dir_all(directory).unwrap();
    }
    for file in [&hlae, &hook, &game, &steam] {
        fs::write(file, b"stub").unwrap();
    }
    let demo = root.path().join("major.dem");
    let commands = artifacts.join("vibe_cs_commands.xml");
    let bridge = artifacts.join("vibe_cs_bridge.js");
    fs::write(&demo, b"demo").unwrap();
    fs::write(&commands, b"commands").unwrap();
    fs::write(&bridge, b"bridge").unwrap();
    let bootstrap =
        compile_hlae_managed_session_bootstrap(&job, &demo, &commands, &bridge).unwrap();
    fs::write(bootstrap.path(), bootstrap.contents()).unwrap();
    let profile = build_hlae_launch_profile(
        &HlaeInstallation {
            root: installation_root,
            executable: hlae,
            source2_hook: hook,
            source: HlaeDiscoverySource::Managed,
        },
        &game,
        &steam,
        &job,
        LaunchResolution {
            width: 1_920,
            height: 1_080,
        },
    )
    .unwrap();

    let invocation = build_hlae_managed_session_invocation(&profile, &bootstrap).unwrap();
    let arguments = invocation.arguments();
    let cmdline_index = arguments
        .iter()
        .position(|value| value == "-cmdLine")
        .unwrap();
    assert_eq!(
        arguments[cmdline_index + 1],
        OsString::from(format!(
            "-steam -insecure +sv_lan 1 -console -sw -w 1920 -h 1080 \
             -afxDisableSteamStorage +mirv_cmd clear +mirv_cmd load \"{}\" \
             +mirv_cmd enabled 1 +mirv_script_load \"{}\" +playdemo \"{}\"",
            commands.display(),
            bridge.display(),
            demo.display(),
        ))
    );
    assert_eq!(bootstrap.path(), job.join("cfg/autoexec.cfg"));
}

#[cfg(windows)]
#[test]
fn managed_bootstrap_never_emits_verbatim_windows_console_paths() {
    let root = tempfile::tempdir().unwrap();
    let job = root.path().join("job");
    fs::create_dir_all(&job).unwrap();
    let demo = root.path().join("major.dem");
    let commands = job.join("vibe_cs_commands.xml");
    let bridge = job.join("vibe_cs_bridge.js");
    fs::write(&demo, b"demo").unwrap();
    fs::write(&commands, b"commands").unwrap();
    fs::write(&bridge, b"bridge").unwrap();

    let bootstrap = compile_hlae_managed_session_bootstrap(
        &fs::canonicalize(&job).unwrap(),
        &fs::canonicalize(&demo).unwrap(),
        &fs::canonicalize(&commands).unwrap(),
        &fs::canonicalize(&bridge).unwrap(),
    )
    .unwrap();

    assert!(!bootstrap.contents().contains(r"\\?\"));
}
