// Generated by Vibe CS for HLAE 2.191.1 mirv-script. Offline demo playback only.
// The host owns process identity, total-tick verification, and tick-window acceptance.
{
    const WS_ADDRESS = __WS_ADDRESS_JSON__;
    const SESSION_TOKEN = __SESSION_TOKEN_JSON__;
    let EXPECTED_OBSERVER_STEAM_ID = __EXPECTED_OBSERVER_STEAM_ID_JSON__;
    let FIXED_SPEC_PLAYER_COMMAND = __FIXED_SPEC_PLAYER_COMMAND_JSON__;
    const EXPECTED_OBSERVER_MODE_IN_EYE = __EXPECTED_OBSERVER_MODE_IN_EYE__;
    const VERIFIED_TOTAL_TICKS = __VERIFIED_TOTAL_TICKS__;
    let SEEK_TARGET_TICK = __SEEK_TARGET_TICK__;
    let SEEK_COMPLETION_MAX_TICK = __SEEK_COMPLETION_MAX_TICK__;
    let FIXED_SEEK_COMMAND = __FIXED_SEEK_COMMAND_JSON__;
    let CAPTURE_START_TICK = __CAPTURE_START_TICK__;
    let CAPTURE_START_MAX_TICK = __CAPTURE_START_MAX_TICK__;
    let CAPTURE_END_TICK = __CAPTURE_END_TICK__;
    let CAPTURE_END_MAX_TICK = __CAPTURE_END_MAX_TICK__;
    const EVENT_ID = "vibe-cs/managed-bridge";
    const FRAME_START = SOURCESDK_CS2.ClientFrameStage_t.FRAME_START;
    const FRAME_RENDER_PASS = SOURCESDK_CS2.ClientFrameStage_t.FRAME_RENDER_PASS;
    const MAX_MESSAGE_BYTES = 16384;
    const MAX_TAKES = __MAX_TAKES__;
    const MAX_TICK = __MAX_TICK__;
    const MAX_PATH_BYTES = 1024;
    const MAX_QUEUE_MESSAGES = 32;
    const MAX_CONNECT_ATTEMPTS = 10;
    const CONNECT_ATTEMPT_TIMEOUT_MS = 5000;
    const CONNECT_RETRY_INTERVAL_MS = 500;
    const DEMO_EVIDENCE_TIMEOUT_MS = 30000;
    const SEEK_TIMEOUT_MS = 30000;
    const CAPTURE_OBSERVATION_TIMEOUT_MS = 5000;
    const HEARTBEAT_INTERVAL_MS = 1000;

    let nextSequence = 1;
    let expectedControlSequence = 1;
    let activeTakeIndex = 0;
    let connectAttempts = 0;
    let connectGeneration = 0;
    let connectAttemptDeadlineMs = 0;
    let nextConnectAtMs = 0;
    let demoEvidenceDeadlineMs = 0;
    let seekDeadlineMs = 0;
    let lastHeartbeatAtMs = 0;
    let connecting = false;
    let connected = false;
    let terminal = false;
    let closingAfterQueue = false;
    let demoReported = false;
    let seekRequested = false;
    let seekCompleted = false;
    let observerVerified = false;
    let capturing = false;
    let awaitingControl = false;
    let pendingRecordStart = null;
    let pendingRecordEndDeadlineMs = 0;
    let socketIn = null;
    let socketOut = null;
    let sending = false;
    const outboundQueue = [];

    function utf8ByteLength(value) {
        let bytes = 0;
        for (let index = 0; index < value.length; index += 1) {
            const code = value.charCodeAt(index);
            if (code < 0x80) bytes += 1;
            else if (code < 0x800) bytes += 2;
            else if (code >= 0xd800 && code <= 0xdbff && index + 1 < value.length) {
                const low = value.charCodeAt(index + 1);
                if (low >= 0xdc00 && low <= 0xdfff) {
                    bytes += 4;
                    index += 1;
                } else bytes += 3;
            } else bytes += 3;
        }
        return bytes;
    }

    function isBoundedPath(value) {
        if (typeof value !== "string" || value.length === 0) return false;
        if (utf8ByteLength(value) > MAX_PATH_BYTES) return false;
        for (let index = 0; index < value.length; index += 1) {
            const code = value.charCodeAt(index);
            if (code < 0x20 || code === 0x7f) return false;
        }
        return true;
    }

    function hasExactKeys(value, expectedKeys) {
        if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
        const actualKeys = Object.keys(value);
        if (actualKeys.length !== expectedKeys.length) return false;
        for (const key of expectedKeys) {
            if (!Object.prototype.hasOwnProperty.call(value, key)) return false;
        }
        return true;
    }

    function isBoundedNonNegativeInteger(value) {
        return Number.isSafeInteger(value) && value >= 0 && value <= MAX_TICK;
    }

    function isCanonicalSteamId64(value) {
        if (typeof value !== "string" || value.length !== 17) return false;
        for (let index = 0; index < value.length; index += 1) {
            const code = value.charCodeAt(index);
            if (code < 0x30 || code > 0x39) return false;
        }
        return value !== "00000000000000000";
    }

    function isValidObserverControl(observer) {
        if (observer === null) return true;
        return hasExactKeys(observer, ["steamId64", "spectatorSlot"])
            && isCanonicalSteamId64(observer.steamId64)
            && Number.isSafeInteger(observer.spectatorSlot)
            && observer.spectatorSlot >= 1
            && observer.spectatorSlot <= 64;
    }

    function isValidAdvanceControl(control) {
        if (!hasExactKeys(control, [
            "kind", "takeIndex", "verifiedTotalTicks", "seekTargetTick",
            "maxStartOvershootTicks", "captureStartTick", "captureEndTick",
            "maxEndOvershootTicks", "observer"
        ])) return false;
        if (control.kind !== "advance_take" || control.takeIndex !== activeTakeIndex + 1
            || control.takeIndex >= MAX_TAKES) return false;
        if (!isBoundedNonNegativeInteger(control.verifiedTotalTicks)
            || !isBoundedNonNegativeInteger(control.seekTargetTick)
            || !isBoundedNonNegativeInteger(control.maxStartOvershootTicks)
            || !isBoundedNonNegativeInteger(control.captureStartTick)
            || !isBoundedNonNegativeInteger(control.captureEndTick)
            || !isBoundedNonNegativeInteger(control.maxEndOvershootTicks)
            || !isValidObserverControl(control.observer)) return false;
        const startMax = control.captureStartTick + control.maxStartOvershootTicks;
        const seekMax = control.seekTargetTick + control.maxStartOvershootTicks;
        const endMax = control.captureEndTick + control.maxEndOvershootTicks;
        return control.verifiedTotalTicks === VERIFIED_TOTAL_TICKS
            && control.verifiedTotalTicks > 0
            && control.seekTargetTick <= control.captureStartTick
            && control.captureStartTick < control.captureEndTick
            && Number.isSafeInteger(startMax) && startMax <= VERIFIED_TOTAL_TICKS
            && Number.isSafeInteger(seekMax) && seekMax <= VERIFIED_TOTAL_TICKS
            && Number.isSafeInteger(endMax) && endMax <= VERIFIED_TOTAL_TICKS;
    }

    function decodeControlMessage(message) {
        if (typeof message !== "string" || utf8ByteLength(message) > MAX_MESSAGE_BYTES) return null;
        let envelope = null;
        try { envelope = JSON.parse(message); } catch (_) { return null; }
        if (!hasExactKeys(envelope, ["sessionToken", "sequence", "control"])
            || envelope.sessionToken !== SESSION_TOKEN
            || envelope.sequence !== expectedControlSequence
            || envelope.control === null
            || typeof envelope.control !== "object"
            || Array.isArray(envelope.control)) return null;
        const control = envelope.control;
        if (control.kind === "advance_take") {
            return isValidAdvanceControl(control) ? control : null;
        }
        if (control.kind === "finish_session") {
            return hasExactKeys(control, ["kind"]) ? control : null;
        }
        return null;
    }

    function applyAdvanceControl(control, nowMs) {
        if (!awaitingControl || capturing || pendingRecordStart !== null
            || pendingRecordEndDeadlineMs !== 0 || !demoReported || !seekCompleted) return false;
        activeTakeIndex = control.takeIndex;
        SEEK_TARGET_TICK = control.seekTargetTick;
        SEEK_COMPLETION_MAX_TICK = control.seekTargetTick + control.maxStartOvershootTicks;
        CAPTURE_START_TICK = control.captureStartTick;
        CAPTURE_START_MAX_TICK = control.captureStartTick + control.maxStartOvershootTicks;
        CAPTURE_END_TICK = control.captureEndTick;
        CAPTURE_END_MAX_TICK = control.captureEndTick + control.maxEndOvershootTicks;
        EXPECTED_OBSERVER_STEAM_ID = control.observer === null ? null : control.observer.steamId64;
        FIXED_SPEC_PLAYER_COMMAND = control.observer === null
            ? null
            : "spec_player " + control.observer.spectatorSlot;
        FIXED_SEEK_COMMAND = "demo_gototick " + SEEK_TARGET_TICK + "; demo_resume";
        seekRequested = false;
        seekCompleted = false;
        observerVerified = false;
        awaitingControl = false;
        executeFixedSeek(nowMs);
        return !terminal && !closingAfterQueue;
    }

    function applyControlMessage(message) {
        const control = decodeControlMessage(message);
        if (control === null || !awaitingControl) {
            failClosed("server control was malformed or arrived outside the take boundary");
            return false;
        }
        if (control.kind === "advance_take") {
            if (!applyAdvanceControl(control, Date.now())) {
                failClosed("typed take advance could not be applied");
                return false;
            }
        } else {
            closingAfterQueue = true;
            drainOutbound();
        }
        expectedControlSequence += 1;
        return true;
    }

    function detachHooks() {
        mirv.events.recordStart.off(EVENT_ID);
        mirv.events.recordEnd.off(EVENT_ID);
        mirv.events.clientFrameStageNotify.off(EVENT_ID);
    }

    function dropSocketParts() {
        if (socketIn !== null) {
            try { socketIn.drop(); } catch (_) { }
            socketIn = null;
        }
        if (socketOut !== null) {
            try { socketOut.drop(); } catch (_) { }
            socketOut = null;
        }
        connected = false;
    }

    function terminateWithoutReport() {
        if (terminal) return;
        terminal = true;
        closingAfterQueue = false;
        outboundQueue.length = 0;
        detachHooks();
        dropSocketParts();
    }

    function encodeEvent(event) {
        const envelope = {
            sessionToken: SESSION_TOKEN,
            sequence: nextSequence,
            event: event
        };
        const encoded = JSON.stringify(envelope);
        if (utf8ByteLength(encoded) > MAX_MESSAGE_BYTES) return null;
        nextSequence += 1;
        return encoded;
    }

    async function closeAfterDrain() {
        detachHooks();
        const output = socketOut;
        if (output !== null) {
            try { await output.close(); } catch (_) {
                terminateWithoutReport();
                return;
            }
        }
        terminal = true;
    }

    async function drainOutbound() {
        if (sending || socketOut === null) return;
        sending = true;
        try {
            while (outboundQueue.length > 0 && socketOut !== null) {
                const message = outboundQueue.shift();
                await socketOut.send(message);
            }
            if (closingAfterQueue) await closeAfterDrain();
        } catch (_) {
            terminateWithoutReport();
        } finally {
            sending = false;
        }
    }

    function failClosed(reason) {
        if (terminal || closingAfterQueue) return;
        if (!connected || socketOut === null) {
            terminateWithoutReport();
            return;
        }
        const encoded = encodeEvent({ kind: "failure_reported", reason: reason });
        if (encoded === null || outboundQueue.length >= MAX_QUEUE_MESSAGES) {
            terminateWithoutReport();
            return;
        }
        outboundQueue.push(encoded);
        closingAfterQueue = true;
        drainOutbound();
    }

    function queueEvent(event) {
        if (terminal || closingAfterQueue || !connected || socketOut === null) return false;
        if (outboundQueue.length >= MAX_QUEUE_MESSAGES) {
            failClosed("outbound queue limit exceeded");
            return false;
        }
        const encoded = encodeEvent(event);
        if (encoded === null) {
            failClosed("outbound message exceeded 16 KiB");
            return false;
        }
        outboundQueue.push(encoded);
        drainOutbound();
        return true;
    }

    function readDemoTickEvidence() {
        const tick = mirv.getDemoTick();
        if (tick === undefined || (typeof tick === "number" && tick < 0)) {
            return { kind: "transient" };
        }
        if (typeof tick !== "number" || !Number.isSafeInteger(tick) || tick > VERIFIED_TOTAL_TICKS) {
            return { kind: "invalid" };
        }
        return { kind: "ready", tick: tick };
    }

    function executeFixedSeek(nowMs) {
        if (seekRequested || terminal || closingAfterQueue) return;
        try {
            mirv.exec(FIXED_SEEK_COMMAND);
        } catch (_) {
            failClosed("fixed demo seek could not be executed");
            return;
        }
        if (queueEvent({ kind: "seek_requested", target_tick: SEEK_TARGET_TICK })) {
            seekRequested = true;
            seekDeadlineMs = nowMs + SEEK_TIMEOUT_MS;
        }
    }

    function maybeReportDemo(nowMs) {
        if (demoReported || terminal || closingAfterQueue || !connected) return;
        if (nowMs >= demoEvidenceDeadlineMs) {
            failClosed("offline demo evidence timed out");
            return;
        }
        if (!mirv.isPlayingDemo()) return;

        const rawDemoPath = mirv.getDemoFilePath();
        if (rawDemoPath === null) return;
        if (typeof rawDemoPath !== "string" || rawDemoPath.length === 0) {
            failClosed("HLAE reported invalid demo path evidence");
            return;
        }
        let demoPath = null;
        try {
            demoPath = mirv.resolveGamePath(rawDemoPath);
        } catch (_) {
            failClosed("HLAE could not resolve demo path evidence");
            return;
        }
        const evidence = readDemoTickEvidence();
        if (evidence.kind === "transient") return;
        if (!isBoundedPath(demoPath) || evidence.kind !== "ready") {
            failClosed("HLAE reported invalid demo evidence");
            return;
        }
        if (queueEvent({
            kind: "demo_loaded",
            demo_path: demoPath,
            current_tick: evidence.tick,
            total_ticks: VERIFIED_TOTAL_TICKS
        })) {
            demoReported = true;
            executeFixedSeek(nowMs);
        }
    }

    function serviceSeek(nowMs) {
        if (!seekRequested || seekCompleted || terminal || closingAfterQueue) return;
        if (nowMs >= seekDeadlineMs) {
            failClosed("fixed demo seek timed out");
            return;
        }
        const evidence = readDemoTickEvidence();
        if (evidence.kind === "transient") return;
        if (evidence.kind !== "ready") {
            failClosed("HLAE reported invalid seek tick evidence");
            return;
        }
        if (evidence.tick < SEEK_TARGET_TICK || evidence.tick > SEEK_COMPLETION_MAX_TICK) return;
        if (queueEvent({ kind: "seek_completed", current_tick: evidence.tick })) {
            seekCompleted = true;
        }
    }

    function serviceRecordStart(nowMs) {
        if (pendingRecordStart === null || terminal || closingAfterQueue) return;
        if (nowMs >= pendingRecordStart.deadlineMs) {
            failClosed("record-start tick evidence timed out");
            return;
        }
        const evidence = readDemoTickEvidence();
        if (evidence.kind === "transient") return;
        if (evidence.kind !== "ready" || evidence.tick < CAPTURE_START_TICK
            || evidence.tick > CAPTURE_START_MAX_TICK) {
            failClosed("record start preceded the verified capture plan");
            return;
        }
        if (EXPECTED_OBSERVER_STEAM_ID !== null && !observerVerified) {
            failClosed("record start arrived before observer identity was verified");
            return;
        }
        if (EXPECTED_OBSERVER_STEAM_ID !== null) {
            const observer = readObserverEvidence();
            if (observer === null || observer.steamId64 !== EXPECTED_OBSERVER_STEAM_ID
                || observer.mode !== EXPECTED_OBSERVER_MODE_IN_EYE) {
                failClosed("record start observer identity or first-person mode no longer matched the capture plan");
                return;
            }
        }
        if (queueEvent({
            kind: "capture_started",
            output_directory: pendingRecordStart.outputDirectory,
            observed_tick: evidence.tick
        })) {
            pendingRecordStart = null;
            capturing = true;
        }
    }

    function readObserverEvidence() {
        try {
            const localController = mirv.getEntityFromSplitScreenPlayer(0);
            if (localController === null) return null;
            const localPawn = mirv.getEntityFromIndex(
                mirv.getHandleEntryIndex(localController.getPlayerPawnHandle())
            );
            if (localPawn === null) return null;
            const observerTarget = mirv.getEntityFromIndex(
                mirv.getHandleEntryIndex(localPawn.getObserverTargetHandle())
            );
            if (observerTarget === null) return null;
            const observerController = mirv.getEntityFromIndex(
                mirv.getHandleEntryIndex(observerTarget.getPlayerControllerHandle())
            );
            if (observerController === null || !observerController.isPlayerController()) return null;
            const steamId = observerController.getSteamId();
            if (typeof steamId !== "bigint" || steamId <= 0n) return null;
            const mode = localPawn.getObserverMode();
            if (!Number.isSafeInteger(mode) || mode < 0 || mode > 255) return null;
            return { steamId64: steamId.toString(), mode: mode };
        } catch (_) {
            return null;
        }
    }

    function serviceObserverEvidence() {
        if (EXPECTED_OBSERVER_STEAM_ID === null || observerVerified || !seekCompleted
            || terminal || closingAfterQueue) return;
        const observer = readObserverEvidence();
        if (observer === null) return;
        if (observer.steamId64 !== EXPECTED_OBSERVER_STEAM_ID) return;
        if (observer.mode !== EXPECTED_OBSERVER_MODE_IN_EYE) return;
        const tickEvidence = readDemoTickEvidence();
        if (tickEvidence.kind === "transient") return;
        if (tickEvidence.kind !== "ready") {
            failClosed("HLAE reported invalid observer tick evidence");
            return;
        }
        if (queueEvent({
            kind: "observer_verified",
            steam_id64: observer.steamId64,
            observer_mode: observer.mode,
            observed_tick: tickEvidence.tick
        })) {
            observerVerified = true;
        }
    }

    function serviceActiveObserverLock() {
        if (!capturing || EXPECTED_OBSERVER_STEAM_ID === null
            || terminal || closingAfterQueue) return;
        const observer = readObserverEvidence();
        if (observer === null || observer.steamId64 !== EXPECTED_OBSERVER_STEAM_ID
            || observer.mode !== EXPECTED_OBSERVER_MODE_IN_EYE) {
            failClosed("active capture observer identity or first-person mode drifted");
        }
    }

    function serviceFixedSpectatorSlotLock() {
        if (!capturing || FIXED_SPEC_PLAYER_COMMAND === null
            || terminal || closingAfterQueue) return;
        try {
            mirv.exec(FIXED_SPEC_PLAYER_COMMAND);
        } catch (_) {
            failClosed("fixed parser-backed spectator-slot lock failed");
        }
    }

    function serviceRecordEnd(nowMs) {
        if (pendingRecordEndDeadlineMs === 0 || terminal || closingAfterQueue) return;
        if (nowMs >= pendingRecordEndDeadlineMs) {
            failClosed("record-end tick evidence timed out");
            return;
        }
        const evidence = readDemoTickEvidence();
        if (evidence.kind === "transient") return;
        if (evidence.kind !== "ready" || evidence.tick < CAPTURE_END_TICK
            || evidence.tick > CAPTURE_END_MAX_TICK) {
            failClosed("record end preceded the verified capture plan");
            return;
        }
        if (EXPECTED_OBSERVER_STEAM_ID !== null) {
            const observer = readObserverEvidence();
            if (observer === null || observer.steamId64 !== EXPECTED_OBSERVER_STEAM_ID
                || observer.mode !== EXPECTED_OBSERVER_MODE_IN_EYE) {
                failClosed("record end observer identity or first-person mode no longer matched the capture plan");
                return;
            }
            if (!queueEvent({
                kind: "observer_verified",
                steam_id64: observer.steamId64,
                observer_mode: observer.mode,
                observed_tick: evidence.tick
            })) return;
        }
        if (queueEvent({ kind: "capture_stopped", observed_tick: evidence.tick })) {
            pendingRecordEndDeadlineMs = 0;
            capturing = false;
            awaitingControl = true;
        }
    }

    function serviceCaptureObservations(nowMs) {
        serviceRecordStart(nowMs);
        serviceRecordEnd(nowMs);
    }

    function onRecordStart(event) {
        if (terminal || closingAfterQueue) return;
        if (!connected || !demoReported || !seekCompleted || awaitingControl || capturing
            || pendingRecordStart !== null
            || pendingRecordEndDeadlineMs !== 0 || !mirv.isPlayingDemo() || mirv.isDemoPaused()) {
            failClosed("record start arrived outside a sought offline demo");
            return;
        }
        const outputDirectory = event === null || event === undefined ? null : event.takeFolder;
        if (!isBoundedPath(outputDirectory)) {
            failClosed("record start did not contain a bounded take path");
            return;
        }
        const nowMs = Date.now();
        pendingRecordStart = {
            outputDirectory: outputDirectory,
            deadlineMs: nowMs + CAPTURE_OBSERVATION_TIMEOUT_MS
        };
        serviceRecordStart(nowMs);
    }

    function onRecordEnd() {
        if (terminal || closingAfterQueue) return;
        if (!connected || !capturing || pendingRecordStart !== null
            || pendingRecordEndDeadlineMs !== 0) {
            failClosed("record end arrived without a reported capture start");
            return;
        }
        const nowMs = Date.now();
        pendingRecordEndDeadlineMs = nowMs + CAPTURE_OBSERVATION_TIMEOUT_MS;
        serviceRecordEnd(nowMs);
    }

    async function readIncoming(input) {
        try {
            while (!terminal) {
                const message = await input.next();
                if (message === null) {
                    terminateWithoutReport();
                    return;
                }
                if (!applyControlMessage(message)) return;
            }
        } catch (_) {
            terminateWithoutReport();
        }
    }

    async function discardLateConnection(pair) {
        try { await pair.out.close(); } catch (_) { }
        try { pair.in.drop(); } catch (_) { }
        try { pair.out.drop(); } catch (_) { }
    }

    function acceptConnection(pair, generation) {
        if (terminal || generation !== connectGeneration || !connecting) {
            discardLateConnection(pair);
            return;
        }
        const nowMs = Date.now();
        connecting = false;
        connected = true;
        demoEvidenceDeadlineMs = nowMs + DEMO_EVIDENCE_TIMEOUT_MS;
        lastHeartbeatAtMs = nowMs;
        socketIn = pair.in;
        socketOut = pair.out;
        queueEvent({ kind: "heartbeat" });
        maybeReportDemo(nowMs);
        readIncoming(socketIn);
    }

    function startConnectionAttempt(nowMs) {
        if (terminal || connected || connecting) return;
        if (connectAttempts >= MAX_CONNECT_ATTEMPTS) {
            terminateWithoutReport();
            return;
        }
        connectAttempts += 1;
        connectGeneration += 1;
        const generation = connectGeneration;
        connecting = true;
        connectAttemptDeadlineMs = nowMs + CONNECT_ATTEMPT_TIMEOUT_MS;
        mirv.connect_async(WS_ADDRESS).then(
            (pair) => acceptConnection(pair, generation),
            (_) => {
                if (terminal || generation !== connectGeneration) return;
                connecting = false;
                nextConnectAtMs = Date.now() + CONNECT_RETRY_INTERVAL_MS;
                if (connectAttempts >= MAX_CONNECT_ATTEMPTS) terminateWithoutReport();
            }
        );
    }

    function serviceConnection(nowMs) {
        if (connected || terminal) return;
        if (connecting && nowMs >= connectAttemptDeadlineMs) {
            connecting = false;
            connectGeneration += 1;
            nextConnectAtMs = nowMs + CONNECT_RETRY_INTERVAL_MS;
            if (connectAttempts >= MAX_CONNECT_ATTEMPTS) {
                terminateWithoutReport();
                return;
            }
        }
        if (!connecting && nowMs >= nextConnectAtMs) startConnectionAttempt(nowMs);
    }

    function onClientFrameStageNotify(event) {
        if (terminal) return;
        if (event.curStage === FRAME_START && event.isBefore) {
            const nowMs = Date.now();
            serviceConnection(nowMs);
            if (connected && !closingAfterQueue) {
                maybeReportDemo(nowMs);
                serviceSeek(nowMs);
                serviceObserverEvidence();
                serviceActiveObserverLock();
                serviceCaptureObservations(nowMs);
                if (demoReported && !mirv.isPlayingDemo()) {
                    failClosed("demo playback ended before bridge finalization");
                } else if (capturing && pendingRecordEndDeadlineMs === 0 && mirv.isDemoPaused()) {
                    failClosed("demo paused while HLAE was recording");
                } else if (nowMs - lastHeartbeatAtMs >= HEARTBEAT_INTERVAL_MS) {
                    if (queueEvent({ kind: "heartbeat" })) lastHeartbeatAtMs = nowMs;
                }
            }
            mirv.run_jobs();
            mirv.run_jobs_async();
        }
        if (event.curStage === FRAME_START && !event.isBefore) {
            serviceFixedSpectatorSlotLock();
        }
        if (event.curStage === FRAME_RENDER_PASS && event.isBefore && connected && socketOut !== null) {
            drainOutbound();
        }
    }

    mirv.events.recordStart.off(EVENT_ID);
    mirv.events.recordEnd.off(EVENT_ID);
    mirv.events.clientFrameStageNotify.off(EVENT_ID);
    mirv.events.recordStart.on(EVENT_ID, onRecordStart);
    mirv.events.recordEnd.on(EVENT_ID, onRecordEnd);
    mirv.events.clientFrameStageNotify.on(EVENT_ID, onClientFrameStageNotify);
}
