use std::{collections::BTreeMap, fmt::Write as _, path::Path};

use crate::validate::{validate_hlae_plan, validate_safe_path};
use crate::{
    CameraShot, CompiledHlaePlan, GeneratedArtifact, HLAE_PLAN_SCHEMA_VERSION, HlaeError,
    HlaeInstallation, HlaeLaunchProfile, HlaePlan, HlaePlanMode, HlaeSafetyPolicy,
    LaunchResolution, PositionInterpolation, RotationInterpolation,
};

const COMMAND_FILE_NAME: &str = "vibe_cs_commands.xml";
const BOOTSTRAP_FILE_NAME: &str = "vibe_cs_hlae.cfg";
const MAXIMUM_COMPILED_ARTIFACT_BYTES: usize = 16 * 1024 * 1024;

/// Compiles a validated plan into reviewable text artifacts without writing or executing them.
///
/// # Errors
///
/// Returns [`HlaeError`] when the artifact directory or any typed plan value
/// violates the bounded planning contract.
pub fn compile_hlae_plan(
    plan: &HlaePlan,
    artifact_directory: &Path,
) -> Result<CompiledHlaePlan, HlaeError> {
    validate_safe_path(artifact_directory, "artifactDirectory", true)?;
    let notices = validate_hlae_plan(plan)?;
    let first_tick = plan
        .shots
        .first()
        .ok_or_else(|| HlaeError::InvalidPlan("a plan must contain a shot".to_owned()))?
        .start_tick;
    let last_tick = plan
        .shots
        .last()
        .ok_or_else(|| HlaeError::InvalidPlan("a plan must contain a shot".to_owned()))?
        .end_tick;

    let camera_paths = plan
        .shots
        .iter()
        .map(|shot| {
            let path = artifact_directory.join(format!("camera_{}.xml", shot.id));
            GeneratedArtifact {
                path,
                media_type: "application/xml".to_owned(),
                contents: compile_camera_path(shot, plan.tick_rate),
            }
        })
        .collect::<Vec<_>>();
    let command_path = artifact_directory.join(COMMAND_FILE_NAME);
    let bootstrap_path = artifact_directory.join(BOOTSTRAP_FILE_NAME);
    let command_system = GeneratedArtifact {
        path: command_path.clone(),
        media_type: "application/xml".to_owned(),
        contents: compile_command_system(plan, &camera_paths),
    };
    let seek_tick = first_tick.saturating_sub(plan.pre_roll_ticks);
    let bootstrap_config = GeneratedArtifact {
        path: bootstrap_path,
        media_type: "text/plain".to_owned(),
        contents: format!(
            "// Generated by Vibe CS. Review before running inside an offline demo.\n\
             // This file never enables trusted or VAC-protected play.\n\
             mirv_cmd clear\n\
             mirv_cmd load \"{}\"\n\
             mirv_cmd enabled 1\n\
             demo_gototick {seek_tick}\n\
             demo_resume\n",
            console_path(&command_path)
        ),
    };

    let compiled = CompiledHlaePlan {
        schema_version: HLAE_PLAN_SCHEMA_VERSION,
        mode: plan.mode,
        first_tick,
        last_tick,
        bootstrap_config,
        command_system,
        camera_paths,
        notices,
    };
    let total_bytes = std::iter::once(&compiled.bootstrap_config)
        .chain(std::iter::once(&compiled.command_system))
        .chain(compiled.camera_paths.iter())
        .try_fold(0_usize, |total, artifact| {
            total.checked_add(artifact.contents.len())
        });
    if total_bytes.is_none_or(|total| total > MAXIMUM_COMPILED_ARTIFACT_BYTES) {
        return Err(HlaeError::InvalidPlan(format!(
            "compiled HLAE artifacts exceed the {MAXIMUM_COMPILED_ARTIFACT_BYTES} byte limit"
        )));
    }
    Ok(compiled)
}

/// Creates the fixed, `-insecure` custom-loader profile documented by HLAE.
///
/// No free-form launch option is accepted, so an AI response cannot inject a
/// switch, console command, environment variable, or shell expression.
///
/// # Errors
///
/// Returns [`HlaeError`] when an executable, path, or resolution is invalid.
pub fn build_hlae_launch_profile(
    installation: &HlaeInstallation,
    cs2_executable: &Path,
    moviemaking_config_root: &Path,
    resolution: LaunchResolution,
) -> Result<HlaeLaunchProfile, HlaeError> {
    if !installation.executable.is_file()
        || !installation.source2_hook.is_file()
        || !installation
            .executable
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.eq_ignore_ascii_case("HLAE.exe"))
        || !installation
            .source2_hook
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.eq_ignore_ascii_case("AfxHookSource2.dll"))
    {
        return Err(HlaeError::InvalidInstallation(
            "HLAE.exe or x64/AfxHookSource2.dll is invalid".to_owned(),
        ));
    }
    validate_safe_path(cs2_executable, "gameExecutable", true)?;
    validate_safe_path(moviemaking_config_root, "moviemakingConfigRoot", true)?;
    if !cs2_executable.is_file()
        || !cs2_executable
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.eq_ignore_ascii_case("cs2.exe"))
    {
        return Err(HlaeError::InvalidInstallation(
            "game executable must be an existing cs2.exe".to_owned(),
        ));
    }
    if !(320..=16_384).contains(&resolution.width) || !(240..=16_384).contains(&resolution.height) {
        return Err(HlaeError::InvalidPlan(
            "launch resolution is outside the supported range".to_owned(),
        ));
    }

    let mut environment = BTreeMap::new();
    environment.insert(
        "USRLOCALCSGO".to_owned(),
        moviemaking_config_root.to_string_lossy().into_owned(),
    );
    Ok(HlaeLaunchProfile {
        hlae_executable: installation.executable.clone(),
        hook_library: installation.source2_hook.clone(),
        game_executable: cs2_executable.to_path_buf(),
        arguments: vec![
            "-steam".to_owned(),
            "-insecure".to_owned(),
            "+sv_lan".to_owned(),
            "1".to_owned(),
            "-console".to_owned(),
            "-sw".to_owned(),
            "-w".to_owned(),
            resolution.width.to_string(),
            "-h".to_owned(),
            resolution.height.to_string(),
            "-afxDisableSteamStorage".to_owned(),
        ],
        environment,
        safety: HlaeSafetyPolicy {
            insecure_mode_required: true,
            vac_servers_prohibited: true,
            demo_playback_only: true,
        },
    })
}

fn compile_camera_path(shot: &CameraShot, tick_rate: f64) -> String {
    let position = match shot.position_interpolation {
        PositionInterpolation::Linear => "linear",
        PositionInterpolation::Cubic => "cubic",
    };
    let rotation = match shot.rotation_interpolation {
        RotationInterpolation::SphericalLinear => "sLinear",
        RotationInterpolation::SphericalCubic => "sCubic",
    };
    let mut xml = format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\
         <campath positionInterp=\"{position}\" rotationInterp=\"{rotation}\" fovInterp=\"cubic\">\n\
         <points>\n"
    );
    for keyframe in &shot.keyframes {
        let relative_tick = u32::try_from(keyframe.tick - shot.start_tick).unwrap_or(u32::MAX);
        let time = f64::from(relative_tick) / tick_rate;
        writeln!(
            xml,
            "<p t=\"{time:.6}\" x=\"{:.6}\" y=\"{:.6}\" z=\"{:.6}\" fov=\"{:.6}\" rx=\"{:.6}\" ry=\"{:.6}\" rz=\"{:.6}\" />",
            keyframe.position.x,
            keyframe.position.y,
            keyframe.position.z,
            keyframe.fov,
            keyframe.rotation.roll,
            keyframe.rotation.pitch,
            keyframe.rotation.yaw
        )
        .expect("writing to String cannot fail");
    }
    xml.push_str("</points>\n</campath>\n");
    xml
}

fn compile_command_system(plan: &HlaePlan, camera_paths: &[GeneratedArtifact]) -> String {
    let first_tick = plan.shots.first().map_or(0, |shot| shot.start_tick);
    let last_tick = plan.shots.last().map_or(0, |shot| shot.end_tick);
    let mut commands = Vec::new();

    if plan.mode == HlaePlanMode::Capture {
        commands.push((first_tick, capture_start_command(plan)));
    }
    for (index, (shot, camera)) in plan.shots.iter().zip(camera_paths).enumerate() {
        let mut start = format!(
            "mirv_campath clear; mirv_campath load \"{}\"; mirv_campath edit start; mirv_fov default; mirv_campath enabled 1",
            console_path(&camera.path)
        );
        if plan.mode == HlaePlanMode::Preview {
            start.push_str("; mirv_campath draw enabled 1");
        }
        commands.push((shot.start_tick, start));
        let has_contiguous_next = plan
            .shots
            .get(index + 1)
            .is_some_and(|next| next.start_tick == shot.end_tick);
        if !has_contiguous_next {
            commands.push((
                shot.end_tick,
                "mirv_campath enabled 0; mirv_campath draw enabled 0".to_owned(),
            ));
        }
    }
    if plan.mode == HlaePlanMode::Capture {
        commands.push((last_tick, capture_stop_command(plan)));
    }
    commands.sort_by_key(|(tick, _)| *tick);

    let mut xml =
        String::from("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<commandSystem>\n<commands>\n");
    for (tick, command) in commands {
        writeln!(
            xml,
            "<c tick=\"{tick}\"><body>{}</body></c>",
            xml_text(&command)
        )
        .expect("writing to String cannot fail");
    }
    xml.push_str("</commands>\n</commandSystem>\n");
    xml
}

fn capture_start_command(plan: &HlaePlan) -> String {
    let mut commands = vec![
        format!(
            "mirv_streams record name \"{}\"",
            console_path(&plan.output_directory)
        ),
        format!("mirv_streams record fps {}", plan.capture.fps),
        format!(
            "mirv_streams record startMovieWav {}",
            u8::from(plan.capture.record_wav)
        ),
        "mirv_streams settings edit afxDefault settings afxClassic".to_owned(),
        format!(
            "mirv_streams record screen enabled {}",
            u8::from(plan.capture.layers.screen)
        ),
    ];
    if plan.capture.layers.world {
        commands.extend([
            "mirv_streams remove vibe_world".to_owned(),
            "mirv_streams add normal vibe_world".to_owned(),
            "mirv_streams edit vibe_world capture beforeUi".to_owned(),
            "mirv_streams edit vibe_world settings afxClassic".to_owned(),
        ]);
    }
    if plan.capture.layers.depth {
        commands.extend([
            "mirv_streams remove vibe_depth".to_owned(),
            "mirv_streams add depth vibe_depth".to_owned(),
            "mirv_streams edit vibe_depth captureType depthF".to_owned(),
            "mirv_streams edit vibe_depth depthChannels gray".to_owned(),
            "mirv_streams edit vibe_depth depthMode pyramidalLinear".to_owned(),
            "mirv_streams edit vibe_depth settings afxClassic".to_owned(),
        ]);
    }
    commands.push("mirv_streams record start".to_owned());
    commands.join("; ")
}

fn capture_stop_command(plan: &HlaePlan) -> String {
    let mut commands = vec![
        "mirv_streams record end".to_owned(),
        "mirv_campath enabled 0".to_owned(),
        "mirv_campath draw enabled 0".to_owned(),
        "mirv_streams record screen enabled 0".to_owned(),
    ];
    if plan.capture.layers.world {
        commands.push("mirv_streams remove vibe_world".to_owned());
    }
    if plan.capture.layers.depth {
        commands.push("mirv_streams remove vibe_depth".to_owned());
    }
    commands.join("; ")
}

fn console_path(path: &Path) -> String {
    path.to_string_lossy().replace('/', "\\")
}

fn xml_text(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        CameraKeyframe, CameraPosition, CameraRotation, CameraShot, CaptureLayers, CaptureSettings,
        HlaeDiscoverySource,
    };
    use std::path::PathBuf;

    fn plan(mode: HlaePlanMode, output: PathBuf) -> HlaePlan {
        HlaePlan {
            schema_version: HLAE_PLAN_SCHEMA_VERSION,
            mode,
            tick_rate: 64.0,
            demo_path: PathBuf::from("match.dem"),
            output_directory: output,
            pre_roll_ticks: 128,
            capture: CaptureSettings {
                layers: CaptureLayers {
                    screen: true,
                    world: true,
                    depth: true,
                },
                ..CaptureSettings::default()
            },
            shots: vec![CameraShot {
                id: "opening".to_owned(),
                start_tick: 1_000,
                end_tick: 1_300,
                position_interpolation: PositionInterpolation::Cubic,
                rotation_interpolation: RotationInterpolation::SphericalCubic,
                keyframes: [1_000, 1_100, 1_200, 1_300]
                    .into_iter()
                    .map(|tick| CameraKeyframe {
                        tick,
                        position: CameraPosition {
                            x: 1.0,
                            y: 2.0,
                            z: 3.0,
                        },
                        rotation: CameraRotation {
                            pitch: 4.0,
                            yaw: 5.0,
                            roll: 6.0,
                        },
                        fov: 90.0,
                    })
                    .collect(),
            }],
        }
    }

    #[test]
    fn preview_is_a_non_recording_dry_run() {
        let root = tempfile::tempdir().unwrap();
        let compiled = compile_hlae_plan(
            &plan(HlaePlanMode::Preview, root.path().join("capture")),
            root.path(),
        )
        .unwrap();

        assert!(
            compiled
                .command_system
                .contents
                .contains("mirv_campath load")
        );
        assert!(
            compiled
                .command_system
                .contents
                .contains("mirv_campath draw enabled 1")
        );
        assert!(!compiled.command_system.contents.contains("record start"));
        assert!(!compiled.command_system.contents.contains("ffmpeg"));
    }

    #[test]
    fn capture_uses_lossless_sequences_and_fixed_whitelisted_commands() {
        let root = tempfile::tempdir().unwrap();
        let compiled = compile_hlae_plan(
            &plan(HlaePlanMode::Capture, root.path().join("capture")),
            root.path(),
        )
        .unwrap();

        let xml = &compiled.command_system.contents;
        assert!(xml.contains("afxClassic"));
        assert!(xml.contains("vibe_depth"));
        assert!(xml.contains("record start"));
        assert!(xml.contains("record end"));
        assert!(!xml.to_ascii_lowercase().contains("ffmpeg"));
    }

    #[test]
    fn camera_xml_uses_relative_sixty_four_tick_time_and_hlae_axes() {
        let root = tempfile::tempdir().unwrap();
        let compiled = compile_hlae_plan(
            &plan(HlaePlanMode::Preview, root.path().join("capture")),
            root.path(),
        )
        .unwrap();
        let xml = &compiled.camera_paths[0].contents;
        assert!(xml.contains("t=\"1.562500\""));
        assert!(xml.contains("rx=\"6.000000\" ry=\"4.000000\" rz=\"5.000000\""));
    }

    #[test]
    fn camera_xml_uses_the_demo_tick_rate() {
        let root = tempfile::tempdir().unwrap();
        let mut plan = plan(HlaePlanMode::Preview, root.path().join("capture"));
        plan.tick_rate = 128.0;
        let compiled = compile_hlae_plan(&plan, root.path()).unwrap();

        assert!(compiled.camera_paths[0].contents.contains("t=\"0.781250\""));
    }

    #[test]
    fn launch_profile_cannot_drop_insecure_mode() {
        let root = tempfile::tempdir().unwrap();
        let hlae = root.path().join("HLAE.exe");
        let hook = root.path().join("x64/AfxHookSource2.dll");
        let cs2 = root.path().join("cs2.exe");
        std::fs::create_dir_all(hook.parent().unwrap()).unwrap();
        for path in [&hlae, &hook, &cs2] {
            std::fs::write(path, b"stub").unwrap();
        }
        let installation = HlaeInstallation {
            root: root.path().to_path_buf(),
            executable: hlae,
            source2_hook: hook,
            source: HlaeDiscoverySource::Configured,
        };
        let profile = build_hlae_launch_profile(
            &installation,
            &cs2,
            &root.path().join("mmcfg"),
            LaunchResolution {
                width: 1920,
                height: 1080,
            },
        )
        .unwrap();

        assert!(profile.arguments.iter().any(|item| item == "-insecure"));
        assert!(profile.safety.vac_servers_prohibited);
        assert!(profile.safety.demo_playback_only);
    }
}
