//! Fixed startup artifact for one app-managed offline HLAE session.

use std::path::{Path, PathBuf};

use crate::{HLAE_MIRV_BRIDGE_FILE_NAME, HlaeError, validate::validate_safe_path};

/// Startup location Source 2 executes after HLAE has mounted the isolated
/// `USRLOCALCSGO` root into the game's search paths.
pub const HLAE_MANAGED_SESSION_CONFIG_RELATIVE_PATH: &str = "cfg/autoexec.cfg";
const HLAE_MANAGED_COMMAND_SYSTEM_FILE_NAME: &str = "vibe_cs_commands.xml";
const HLAE_MANAGED_SESSION_CONFIG_MAX_BYTES: usize = 16 * 1_024;

/// One process-free, immutable startup config for a managed offline session.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HlaeManagedSessionBootstrap {
    path: PathBuf,
    contents: String,
    command_line_suffix: String,
}

impl HlaeManagedSessionBootstrap {
    /// Returns the exact location that must be published below the job's
    /// isolated moviemaking configuration root.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Returns the fixed, reviewable Source 2 console configuration.
    #[must_use]
    pub fn contents(&self) -> &str {
        &self.contents
    }

    /// Returns the same fixed startup commands encoded for Source 2's
    /// `+command` launch syntax. HLAE registers its commands before handing
    /// the command line to Source 2, avoiding search-path timing races.
    pub(crate) fn command_line_suffix(&self) -> &str {
        &self.command_line_suffix
    }
}

/// Compiles the only console commands needed to load the command schedule and
/// authenticated bridge before opening the parser-verified demo.
///
/// The bridge, rather than this startup file, owns the fixed seek and observes
/// the actual tick reached. No network server command or free-form console text
/// is accepted.
///
/// # Errors
///
/// Returns [`HlaeError`] if the job root or input artifacts are unsafe, linked,
/// missing, outside the managed job, or have an unexpected fixed file type.
pub fn compile_hlae_managed_session_bootstrap(
    job_root: &Path,
    demo_path: &Path,
    command_system_path: &Path,
    bridge_script_path: &Path,
) -> Result<HlaeManagedSessionBootstrap, HlaeError> {
    validate_safe_path(job_root, "managedJobRoot", true)?;
    validate_safe_path(demo_path, "demoPath", true)?;
    validate_safe_path(command_system_path, "commandSystemPath", true)?;
    validate_safe_path(bridge_script_path, "bridgeScriptPath", true)?;
    require_regular(job_root, true, "managed job root")?;
    require_regular(demo_path, false, "demo")?;
    require_regular(command_system_path, false, "command system")?;
    require_regular(bridge_script_path, false, "bridge script")?;

    if !demo_path
        .extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case("dem"))
    {
        return invalid("managed session demo must be a .dem file");
    }
    if command_system_path
        .file_name()
        .and_then(|name| name.to_str())
        != Some(HLAE_MANAGED_COMMAND_SYSTEM_FILE_NAME)
    {
        return invalid("managed command system must use the fixed vibe_cs_commands.xml name");
    }
    if bridge_script_path
        .file_name()
        .and_then(|name| name.to_str())
        != Some(HLAE_MIRV_BRIDGE_FILE_NAME)
    {
        return invalid("managed bridge must use the fixed bridge artifact name");
    }

    let canonical_job = canonicalize(job_root, "canonicalize managed job root")?;
    for (path, label) in [
        (command_system_path, "command system"),
        (bridge_script_path, "bridge script"),
    ] {
        let canonical = canonicalize(path, "canonicalize managed session artifact")?;
        if !canonical.starts_with(&canonical_job) {
            return invalid(format!("managed {label} must remain inside the job root"));
        }
    }

    let command_system = console_path(command_system_path);
    let bridge = console_path(bridge_script_path);
    let demo = console_path(demo_path);
    let contents = format!(
        "// Generated by Vibe CS for one managed, offline HLAE session.\n\
         mirv_cmd clear\n\
         mirv_cmd load \"{}\"\n\
         mirv_cmd enabled 1\n\
         mirv_script_load \"{}\"\n\
         playdemo \"{}\"\n",
        command_system, bridge, demo,
    );
    if contents.len() > HLAE_MANAGED_SESSION_CONFIG_MAX_BYTES {
        return invalid("managed session config exceeds its 16 KiB limit");
    }

    Ok(HlaeManagedSessionBootstrap {
        path: job_root.join(HLAE_MANAGED_SESSION_CONFIG_RELATIVE_PATH),
        contents,
        command_line_suffix: format!(
            "+mirv_cmd clear +mirv_cmd load \"{command_system}\" \
             +mirv_cmd enabled 1 +mirv_script_load \"{bridge}\" +playdemo \"{demo}\""
        ),
    })
}

fn require_regular(path: &Path, directory: bool, label: &str) -> Result<(), HlaeError> {
    let metadata = std::fs::symlink_metadata(path).map_err(|error| HlaeError::ArtifactIo {
        operation: "inspect managed HLAE session path",
        message: error.to_string(),
    })?;
    if metadata.file_type().is_symlink()
        || (directory && !metadata.is_dir())
        || (!directory && !metadata.is_file())
    {
        return invalid(format!("managed {label} must be a regular non-link path"));
    }
    Ok(())
}

fn canonicalize(path: &Path, operation: &'static str) -> Result<PathBuf, HlaeError> {
    std::fs::canonicalize(path).map_err(|error| HlaeError::ArtifactIo {
        operation,
        message: error.to_string(),
    })
}

fn console_path(path: &Path) -> String {
    // Source 2 and HLAE console commands accept regular DOS paths, but do not
    // consistently parse Win32's verbatim `\\?\` namespace emitted by
    // `std::fs::canonicalize`. Keep canonical paths for containment checks and
    // simplify only the trusted representation embedded in the fixed config.
    dunce::simplified(path).to_string_lossy().replace('/', "\\")
}

fn invalid<T>(message: impl Into<String>) -> Result<T, HlaeError> {
    Err(HlaeError::InvalidPlan(message.into()))
}
